# Generated by Django 5.2.4 on 2025-08-18 02:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# shop.migrations.0006_uppercase_name

class Migration(migrations.Migration):

    replaces = [('shop', '0001_initial'), ('shop', '0002_customer_phone_number'), ('shop', '0003_rename_name_customer_full_name'), ('shop', '0004_alter_customer_options'), ('shop', '0005_customer_unique_customer_email_phone'), ('shop', '0006_uppercase_name'), ('shop', '0007_order_created_at'), ('shop', '0008_order_order_created_idx'), ('shop', '0009_rename_customer_client'), ('shop', '0010_auto_20250818_0757')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email', 'phone_number'), name='unique_customer_email_phone'),
        ),
        migrations.RunPython(
            code=shop.migrations.0006_uppercase_name.uppercase_names,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 4, 17, 19, 14589, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_idx'),
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
    ]
