# Generated by Django 5.2.4 on 2025-08-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='full_name',
        ),
    ]
