# Generated by Django 5.2.4 on 2025-08-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email', 'phone_number'), name='unique_customer_email_phone'),
        ),
    ]
