# Generated by Django 5.2.4 on 2025-08-17 03:58

from django.db import migrations


def uppercase_names(apps, schema_editor):
    Customer = apps.get_model('shop', 'Customer')
    for customer in Customer.objects.all():
        customer.full_name = customer.full_name.upper()
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_unique_customer_email_phone'),
    ]

    operations = [
        migrations.RunPython(uppercase_names),
    ]
