# Generated by Django 5.2.4 on 2025-08-17 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_uppercase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 4, 17, 19, 14589, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
