# Generated by Django 5.2.4 on 2025-08-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_order_created_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
    ]
