# Generated by Django 5.2.4 on 2025-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_customer_client'),
    ]

    operations = [
    ]
