# Generated by Django 5.2.4 on 2025-07-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboptimize', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='dboptimize__name_c0c2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='dboptimize__project_287db5_idx'),
        ),
    ]
